# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexuality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='introduction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Uname'),
        ),
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Uname'),
        ),
        migrations.AddField(
            model_name='birth',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Uname'),
        ),
    ]
